name: "Build"

on:
  push:
    branches: ["master"]

jobs:
  autobuild:
    name: Autobuild
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: [ 'java' ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Tell Github Actions that Java 17 exists
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}


      # Autobuild attempts to build any compiled languages  (C/C++, C#, Go, or Java).
      # If this step fails, then you should remove it and run the build manually (see below)
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      
      - name: Build with Gradle
        run: ./gradlew build

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: "/language:${{matrix.language}}"
        
      - name: Archive Artifact
        uses: actions/upload-artifact@v3
        if: success()
        with:
          name: HITWTracker
          path: build/libs/HITWTracker-*.jar
          if-no-files-found: error
